export const ActionTypes = {
    LOGIN: "LOGIN",
    SIGNUP: "SIGNUP",
    CREATE_QUESTION:"CREATE_QUESTION",
    GET_QUESTION:"GET_QUESTION",
   UPDATE_QUESTION:"UPDATE_QUESTION",
   DELETE_QUESTION:"DELETE_QUESTION",
   CREATE_TRANSLATION:"CREATE_TRANSLATION",
    GET_TRANSLATION:"GET_TRANSLATION",
   UPDATE_TRANSLATION:"UPDATE_TRANSLATION",
   DELETE_TRANSLATION:"DELETE_TRANSLATION"
  };
